FROM debian:12.10
ARG JDK_DIR=/jdk
ARG JDKFILE=openjdk-22.0.2_linux-x64_bin.tar.gz
ARG JDKPATH=jdk-22.0.2
COPY simsun.ttc /usr/share/fonts/
RUN apt-get update && apt-get install -y locales fontconfig && rm -rf /var/lib/apt/lists/* \
    && localedef -i zh_CN -c -f UTF-8 -A /usr/share/locale/locale.alias zh_CN.UTF-8 \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' >/etc/timezone \
    && fc-cache -fv\
    && mkdir $JDK_DIR
ADD $JDKFILE $JDK_DIR
# 设置环境变量
ENV LANG zh_CN.utf8
ENV JAVA_HOME $JDK_DIR/$JDKPATH
ENV CLASSPATH .:${JAVA_HOME}/lib
ENV PATH ${JAVA_HOME}/bin:$PATH